// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  alternate_grid: defineAsyncComponent(
    () => import("./AlternateGrid/index.vue")
  ),
  app_footer: defineAsyncComponent(() => import("./AppFooter/index.vue")),
  contact_form: defineAsyncComponent(() => import("./ContactForm/index.vue")),
  gallery: defineAsyncComponent(() => import("./Gallery/index.vue")),
  heading: defineAsyncComponent(() => import("./Heading/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  main_menu: defineAsyncComponent(() => import("./MainMenu/index.vue")),
  menu_item: defineAsyncComponent(() => import("./MenuItem/index.vue")),
  multi_column: defineAsyncComponent(() => import("./MultiColumn/index.vue")),
  newsletter: defineAsyncComponent(() => import("./Newsletter/index.vue")),
  product_carousel: defineAsyncComponent(
    () => import("./ProductCarousel/index.vue")
  ),
  product_gallery: defineAsyncComponent(
    () => import("./ProductGallery/index.vue")
  ),
  quotes: defineAsyncComponent(() => import("./Quotes/index.vue")),
  related_products: defineAsyncComponent(
    () => import("./RelatedProducts/index.vue")
  ),
  skew_hero: defineAsyncComponent(() => import("./SkewHero/index.vue")),
  sticky_menu: defineAsyncComponent(() => import("./StickyMenu/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
  video: defineAsyncComponent(() => import("./Video/index.vue")),
  video_grid: defineAsyncComponent(() => import("./VideoGrid/index.vue")),
  warning: defineAsyncComponent(() => import("./Warning/index.vue")),
});
