// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  app_footer: defineAsyncComponent(() => import("./AppFooter/index.vue")),
  contact_form: defineAsyncComponent(() => import("./ContactForm/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  main_menu: defineAsyncComponent(() => import("./MainMenu/index.vue")),
  multi_column: defineAsyncComponent(() => import("./MultiColumn/index.vue")),
  product_carousel: defineAsyncComponent(
    () => import("./ProductCarousel/index.vue")
  ),
  related_products: defineAsyncComponent(
    () => import("./RelatedProducts/index.vue")
  ),
  skew_hero: defineAsyncComponent(() => import("./SkewHero/index.vue")),
  sticky_menu: defineAsyncComponent(() => import("./StickyMenu/index.vue")),
});
